from spice.runtime.store import LocalJsonStore
from spice.runtime.doctor import (
    DoctorCheck,
    DoctorReport,
    render_doctor_report,
    run_doctor,
)
from spice.runtime.setup_wizard import SetupWizardResult, run_setup_wizard
from spice.runtime.full_loop_preview import (
    RuntimeFullLoopPreviewResult,
    build_runtime_full_loop_preview,
    render_runtime_full_loop_preview_text,
)
from spice.runtime.dry_run_executor import (
    DryRunExecutionResult,
    execute_dry_run_approval,
    render_dry_run_execution_text,
)
from spice.runtime.sdep_subprocess_executor import (
    SDEPSubprocessExecutionResult,
    execute_sdep_subprocess_approval,
    render_sdep_subprocess_execution_text,
)
from spice.runtime.executor_runtime import (
    ExecutorRuntimeSpec,
    ResolvedExecutorRuntime,
    executor_runtime_specs,
    resolve_executor_runtime,
    resolve_executor_runtime_from_config,
)
from spice.runtime.executor_discovery import (
    ExecutorCLIDetection,
    detect_executor_cli,
    detect_known_executor_clis,
)
from spice.runtime.executor_status import (
    build_executor_status,
    render_executor_doctor,
    render_executor_list,
)
from spice.runtime.claude_code_provider import execute_claude_code_approval
from spice.runtime.codex_provider import execute_codex_approval
from spice.runtime.hermes_provider import execute_hermes_approval
from spice.runtime.context_debug import (
    compile_workspace_decision_context_payload,
    render_decision_context_text,
)
from spice.runtime.interactive_shell import (
    InteractiveShellResult,
    render_interactive_shell_header,
    render_interactive_shell_help,
    run_interactive_shell,
)
from spice.runtime.tui import SpiceTUIShell, run_tui_shell
from spice.runtime.providers import (
    ClaudeCodeExecutorProvider,
    CodexExecutorProvider,
    DryRunExecutorProvider,
    ExecutorProvider,
    HermesExecutorProvider,
    LocalJsonStoreProvider,
    ManualInputProvider,
    PerceptionProvider,
    RuntimeProviderDescriptor,
    SDEPSubprocessExecutorProvider,
    StoreProvider,
    default_runtime_provider_descriptors,
)
from spice.perception import (
    OpenChronicleMCPClient,
    OpenChroniclePerceptionProvider,
    OpenChronicleResult,
    PollPerceptionProvider,
    PollResult,
)
from spice.runtime.approval_flow import (
    ApprovalResolutionResult,
    approve_approval,
    list_approvals,
    load_approval,
    reject_approval,
    render_approval_details,
    render_approval_list,
    render_approval_resolution,
)
from spice.runtime.run_once import (
    RunOnceResult,
    build_manual_intent_observations,
    run_decision_loop_from_observations,
    run_once,
)
from spice.runtime.refine import RefineResult, refine_decision, render_refine_text
from spice.runtime.perceive import (
    PerceiveResult,
    perceive_once,
    perceive_watch,
    render_perceive_text,
)
from spice.runtime.session import (
    DEFAULT_SESSION_ID,
    SessionRecord,
    SessionSearchMatch,
    SessionTimelineEntry,
    append_run_to_session,
    archive_session,
    build_session_timeline,
    delete_session,
    list_sessions,
    load_or_create_session,
    render_session_current,
    render_session_delete_result,
    render_session_list,
    render_session_resume,
    render_session_search,
    render_session_stats,
    render_session_timeline,
    search_sessions,
    session_stats,
)
from spice.runtime.workspace import (
    DEFAULT_WORKSPACE_CONFIG,
    SPICE_DIR_NAME,
    SpiceWorkspaceConfig,
    SpiceWorkspacePaths,
    SpiceWorkspaceSetupReport,
    configure_workspace_llm,
    load_workspace_env,
    load_workspace_config,
    load_workspace_context_compiler,
    load_workspace_memory_provider,
    require_workspace,
    safe_workspace_record_id,
    set_workspace_active_session,
    setup_workspace,
    update_workspace_config,
    validate_workspace_config_update,
    workspace_memory_path,
    workspace_paths,
)

__all__ = [
    "DEFAULT_WORKSPACE_CONFIG",
    "DEFAULT_SESSION_ID",
    "LocalJsonStore",
    "ApprovalResolutionResult",
    "DryRunExecutionResult",
    "DoctorCheck",
    "DoctorReport",
    "ExecutorRuntimeSpec",
    "ExecutorCLIDetection",
    "InteractiveShellResult",
    "RunOnceResult",
    "RefineResult",
    "PerceiveResult",
    "PollResult",
    "RuntimeFullLoopPreviewResult",
    "RuntimeProviderDescriptor",
    "ResolvedExecutorRuntime",
    "SDEPSubprocessExecutionResult",
    "SPICE_DIR_NAME",
    "SetupWizardResult",
    "SessionRecord",
    "SessionSearchMatch",
    "SessionTimelineEntry",
    "DryRunExecutorProvider",
    "ClaudeCodeExecutorProvider",
    "CodexExecutorProvider",
    "ExecutorProvider",
    "HermesExecutorProvider",
    "LocalJsonStoreProvider",
    "ManualInputProvider",
    "OpenChronicleMCPClient",
    "OpenChroniclePerceptionProvider",
    "OpenChronicleResult",
    "PerceptionProvider",
    "PollPerceptionProvider",
    "SDEPSubprocessExecutorProvider",
    "SpiceWorkspaceConfig",
    "SpiceWorkspacePaths",
    "SpiceWorkspaceSetupReport",
    "SpiceTUIShell",
    "StoreProvider",
    "append_run_to_session",
    "archive_session",
    "approve_approval",
    "build_session_timeline",
    "build_manual_intent_observations",
    "build_runtime_full_loop_preview",
    "build_executor_status",
    "configure_workspace_llm",
    "default_runtime_provider_descriptors",
    "execute_dry_run_approval",
    "execute_claude_code_approval",
    "execute_codex_approval",
    "execute_hermes_approval",
    "execute_sdep_subprocess_approval",
    "compile_workspace_decision_context_payload",
    "executor_runtime_specs",
    "detect_executor_cli",
    "detect_known_executor_clis",
    "delete_session",
    "load_workspace_config",
    "load_workspace_context_compiler",
    "load_workspace_env",
    "load_workspace_memory_provider",
    "list_sessions",
    "list_approvals",
    "load_approval",
    "load_or_create_session",
    "reject_approval",
    "render_session_current",
    "render_session_delete_result",
    "render_approval_details",
    "render_approval_list",
    "render_approval_resolution",
    "render_dry_run_execution_text",
    "render_executor_doctor",
    "render_executor_list",
    "render_doctor_report",
    "render_decision_context_text",
    "render_interactive_shell_header",
    "render_interactive_shell_help",
    "render_sdep_subprocess_execution_text",
    "render_session_list",
    "render_session_resume",
    "render_session_search",
    "render_session_stats",
    "render_session_timeline",
    "render_runtime_full_loop_preview_text",
    "require_workspace",
    "run_doctor",
    "run_setup_wizard",
    "safe_workspace_record_id",
    "run_interactive_shell",
    "run_tui_shell",
    "run_decision_loop_from_observations",
    "run_once",
    "refine_decision",
    "render_refine_text",
    "perceive_once",
    "perceive_watch",
    "render_perceive_text",
    "resolve_executor_runtime",
    "resolve_executor_runtime_from_config",
    "search_sessions",
    "session_stats",
    "set_workspace_active_session",
    "setup_workspace",
    "update_workspace_config",
    "validate_workspace_config_update",
    "workspace_memory_path",
    "workspace_paths",
]
